### ISSUE TITLE
3월 31일 오늘의 할 일

### ISSUE THREAD

**Issue by meenoie** [meenoie/testRepo#2]
## 일정
- [x] `9:00` 선배 특강
- [x] `13:00` 협업 특강 오늘도 개발자가 안된다고 말했다..듣기..😵‍💫

## 할 일
- [ ] 협업 특강 복습하기
- [ ] 나는 멋져 3번 외치기
- [ ] 저녁 듣는하게 먹기
- [ ] 협업 특강 끝나고 쉬는 시간에 스트레칭 꼭 하기!!!

**Comment by meenoie** [comment]
이슈 클로즈 실습을 위해 close 합니다!

**Comment by meenoie** [comment]
1. @meenoie @jiwon6635 @tweety-hh @kyeongboo-coder @astinaus @withLeche @ebokyung
2. 커밋 주소: https://github.com/meenoie/testRepo/commit/d4184a7a364782b1f9f8ef97d80637ac73594f31

**Comment by jiwon6635** [comment]
화이팅

**Comment by meenoie** [comment]
#1 
왜 안되조
